### ISSUE TITLE
replace dependency on aiida by dependency on aiida-core?

### ISSUE THREAD

**Issue by ltalirz** [greschd/aiida-strain#1]
https://github.com/greschd/aiida-strain/blob/bee8121b6a7e6c6319e60067ba68a85d8bba135f/setup.json#L19

potentially also with a version selector like
```
aiida-core>=0.12.3,<1.0.0
```
or
```
aiida-core>=1.0.0b6,<2.0.0
```
 (unless this plugin is supposed to work with both versions)

**Comment by greschd** [comment]
The dependency is already "aiida-core" ("aiida" is just in the keywords).

Concerning the version selector: is there a good reason to suspect the plugin would necessarily be broken after the 2.0 release? Instinctively I would have gone with the "library" approach of making the dependencies as open as possible.

**Comment by greschd** [comment]
As an aside, most of my plugins are just about ready for 1.0, it's just happening in a separate branch.

**Comment by ltalirz** [comment]
> The dependency is already "aiida-core" ("aiida" is just in the keywords).

Ah yes - sorry.

> Concerning the version selector: is there a good reason to suspect the plugin would necessarily be broken after the 2.0 release? 

In reality, I would say that the answer is very likely 'yes' (although it is, of course, possible in principle that the plugin will continue to work).

In general, I would prefer if older versions of plugins would remain pip-installable (e.g. if you would like to reproduce some calculation).
One can then always forcefully install a newer aiida-core version afterwards, if that really works.

**Comment by greschd** [comment]
Wouldn't force-installing a different ``aiida-core`` version also work the opposite way -- installing the older version after the plugin is installed?

I'm a bit wary of the risk of having someone who runs 2.0 force-downgraded when installing the plugin. Changing ``aiida-core`` version seems like a bigger deal, and I don't think it should happen accidentally.

On reproducing calculations, maybe we should encourage people to keep ``pip freeze`` files around. I've just recently been bit by not knowing exactly which combination of (my own) plugins worked together..

**Comment by ltalirz** [comment]
> Wouldn't force-installing a different aiida-core version also work the opposite way -- installing the older version after the plugin is installed?

Yes, but if the plugin isn't compatible with the newer version of aiida-core, then the pip-installed version is broken. For example, most if not all plugins that were written before aiida-core 1.0 development started will be broken when 1.0 is released on PyPI.

Hopefully we can avoid this for 2.0 by limiting the aiida-core version.

> I'm a bit wary of the risk of having someone who runs 2.0 force-downgraded when installing the plugin. Changing aiida-core version seems like a bigger deal, and I don't think it should happen accidentally.

I agree that this is not nice - to me, the decision is between a forceful downgrade and ending up with a combination of core and plugin that potentially doesn't work together.
I'd still choose the forceful downgrade but I agree there are arguments for both sides.

@sphuber and @giovannipizzi Do you have some input on this as well? 
It would be very helpful to come to an agreement on this so that we can make a consistent recommendation (during the plugin migration workshop earlier this year, we recommended the upper limit but we can still change this if we think this is the worse option).

> On reproducing calculations, maybe we should encourage people to keep pip freeze files around. I've just recently been bit by not knowing exactly which combination of (my own) plugins worked together..

Yes... thinking about what would be a good "hook" for a `pip freeze`. Perhaps `verdi export`?
The idea being that you're about to share your work with others.
Could be included in the export file for reference purposes.

**Comment by greschd** [comment]
Yeah, neither option is perfect (well, dependency management is hard, who knew :smile:). It depends on whether you think people will just directly install a plugin, or if it's more common to install them onto an existing AiiDA install. In any case, I agree that consistency is key - so I'll follow whatever the consensus is.

Agree, ``verdi export`` seems like a good hook for the ``pip freeze``. Of course it can't be guaranteed that there were no package changes anywhere in between, but it's a pretty good starting point.

**Comment by giovannipizzi** [comment]
My suggestion would be to put in the `<2` in the dependency. My reasoning: 
- for now we don't know what AiiDA 2.0 will look like and we need to assume plugins will break
- as soon as we start formalising what AiiDA 2.0 will be, we'll communicate to plugin developers, who will test the plugin and, in case nothing needs to change, chan release a new version with, e.g., `<3`. This can happen early enough so that there will be enough versions without `<2` to make the risk of downgrading very low (and the case when 2.0 is out and people want to use an older version of the plugin with 2.0 is a bit less common than the other cases, i.e. A) you want to reproduce an old existing environment, and then you have an AiiDA < 1.0, or B) you want to use for production the plugin for 2.0 and you know it works, but then a new release moving for `<2` to `<3` is in order to "say" that you as a developer checked that it works also with AiiDA 2.x)

Open for further discussions, though, if you don't agree
